### ISSUE TITLE
Accessing the docker container (bash) from heroku

### ISSUE THREAD

**Issue by anthony2261** [Alschn/django-react-docker-heroku-template#1]
Hi there, thank you for this wonderful template. I've had an issue where I wanted to create an initial admin user, and I wanted to connect to the live docker container to create a superuser. Couldn't figure out why `heroku ps:exec` always retuned this error:
```
Establishing credentials... error
 ▸    Could not connect to dyno!
 ▸    Check if the dyno is running with `heroku ps'
```
Tried following this section https://devcenter.heroku.com/articles/exec#using-with-docker but it couldn't figure out what the issue was. (Eventually used a migration to create an initial superuser - it's a dummy app)

**Comment by Alschn** [comment]
Hi, @anthony2261. Thank you for submitting an issue. I am glad that you liked the template.

When it comes to this error, I remember having it myself and I don't think I solved it.
However, I think I know why it is occuring. I managed to get inside the container by running `heroku run bash` in dashboard console (https://dashboard.heroku.com/apps/your-app-name > More > Run Console) but I could not execute any commands because everytime I tried, heroku would run commands from the entrypoint (run migrations and **then start gunicorn** - which does not let you run any command because the server is running in this terminal session).

What I suspect is that heroku ps:exec does not work, because everytime you try to get into the container, you spawn a process which runs Dockerfile.prod file.

If that's the case, then you might need to remove those lines from Dockerfile:
https://github.com/Alschn/django-react-docker-heroku-template/blob/1b8eef5e0f993d128e9523784c5eeae2a472c735/Dockerfile.prod#L41-L42

then remove `gunicorn --chdir backend core.wsgi ` from entrypoint.prod
https://github.com/Alschn/django-react-docker-heroku-template/blob/1b8eef5e0f993d128e9523784c5eeae2a472c735/backend/scripts/entrypoint-prod.sh#L1-L5

and define `build`, `release` and `run` phases in `heroku.yml`.

Build phase would just use Dockerfile.prod. In release you would run makemigrations and migrate. In run phase, there would be just a gunicorn command. All of the phases should share `web` image.

You can have a look at my another project and try to implement it yourself or just wait for me to fix things:
https://github.com/Alschn/Beerdegu/blob/dev/backend/scripts/entrypoint-prod.sh
https://github.com/Alschn/Beerdegu/blob/dev/heroku.yml

I will try to publish a new version of this template (on branch template_v2 which has not been pushed yet) tomorrow. I am going to bump frontend packages, replace node-sass with sass, adjust script, dockerfile and heroku.yml files to work.

**Comment by Alschn** [comment]
I have just pushed a newer version of this template. It is available on master branch.
`heroku ps:exec` does not work but you can use `heroku run bash` instead to access docker container in Heroku.

Please check if everything works for you after migrating to the newest template version :)

**Comment by anthony-affinda** [comment]
Awesome!! I've updated my project with your changes, I really hope this gets some more attention :) Merry Christmas!

**Comment by anthony2261** [comment]
Awesome!! I've updated my project with your changes and was able to bash into the container on heroku, thank you for this. I really hope this template gets some more recognition :) Merry Christmas!
